linux-system-roles/nbde_server

- README.md
- defaults/main.yml
- library/nbde_server_tang.py
- playbooks/03-create-new-keys-and-fetch-them.yml
- playbooks/06-nbde-server-create-new-keys-and-deploy-them.yml
- tasks/main-tang.yml
- tests/tests_default.yml
- tests/tests_default_vars.yml
- tests/tests_nbde_server_rotate_keys.yml
- tests/verify-role-results.yml
- tests/verify-tang-results.yml
The behavior is the following:
- if there are no keys, create them
- if there are keys, do not touch them, unless nbde_server_create_keys is
set to `yes', in which case the keys will be rotated and new keys will
be created
> Rename nbde_server_create_keys to nbde_server_rotate_keys

- README.md
The error looks like this:
```
[blockdef-pass] missing closing delimiter
```
The line marked with `####` was too long.  Moved the note to
a separate line.
> fix asciidoc conversion issue

- tasks/main.yml
So that we load the files from the correct place, when the role gets
included in another role.
When this role gets included from a different role, the task checking
out the system to load specific variables for the system may end up
looking in other places and loading a wrong file.
For instance, the nbde_client role includes this one for the testing,
and since it detects the system is e.g. Fedora, it will try to load
Fedora.yml in this role's vars/; however, since it does not exist and
does exist a Fedora.yml somewhere in nbde_client's, it will load that
file instead, which causes problems since the expected variables will
not be set -- in this case, we should load defaults.yml from
nbde_server's vars/.
> Specify path for looking up variables

- library/nbde_server_tang.py
RHELPLAN-69928 	Add a note to each module Doc to indicate it is private
- Adding "WARNING: Do not use this module directly! It is only for role internal use." to nbde_server_tang module DOCUMENTATION.
- Moving detailed descriptions from the choice column to the description/comments column.
> RHELPLAN-68126 Collections - Nbde_server - fixing ansible-test errors

- .github/workflows/tox.yml
- ansible_pytest_extra_requirements.txt
- meta/main.yml
- tests/tests_default_vars.yml
Bug 1989197 - drop support for Ansible 2.8
https://bugzilla.redhat.com/show_bug.cgi?id=1989197
> Drop support for Ansible 2.8 by bumping the Ansible version to 2.9

- CHANGELOG.md
[1.1.5] - 2022-07-19
--------------------
- none
- none
- make all tests work with gather_facts: false (#55)
Ensure the test works when using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml (#56)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#57)
> Version 1.1.5 - CHANGELOG.md [citest skip]

- README.md
- defaults/main.yml
- tasks/tangd-custom-port.yml
- tests/tests_tangd_custom_port.yml
Introduce nbde_server_manage_firewall and nbde_server_manage_selinux to manage the custom ports implemented in "Add support for custom ports (#38)"
- If nbde_server_manage_firewall is set to true, use the firewall role to manage the nbde server port.
- If nbde_server_manage_selinux is set to true, use the selinux role to manage the nbde server port.
Note: this pr adds the two variables to manage the functionality, which is already implemented in "Add support for custom ports (#38)". These variables are added to provide the same api across the roles.
> Introduce nbde_server_manage_firewall and nbde_server_manage_selinux

- CHANGELOG.md
[1.2.0] - 2022-11-01
--------------------
- Add support for custom ports (#38)
- Introduce nbde_server_manage_firewall and nbde_server_manage_selinux
to manage the custom ports implemented in "Add support for custom
ports (#38)"
- If nbde_server_manage_firewall is set to true, use the firewall
role to manage the nbde server port.
- If nbde_server_manage_selinux is set to true, use the selinux
role to manage the nbde server port.
- none
- none
> Version 1.2.0 - CHANGELOG.md [citest skip]

- .ansible-lint
- .yamllint.yml
- .yamllint_defaults.yml
- README.md
- examples/deploy_and_reuse_keys.yml
- examples/lift_keys_from_servers.yml
- examples/redeploy_keys.yml
- examples/simple_deploy.yml
- tests/setup-snapshot.yml
- tests/tests_default.yml
- tests/tests_default_vars.yml
- tests/tests_include_vars_from_parent.yml
- tests/tests_nbde_server_keys_dir.yml
- tests/tests_nbde_server_service_state.yml
- tests/tests_tangd_custom_port.yml
All tasks must be named
Tasks names must begin with uppercase letter
Use `true`/`false` instead of `yes`/`no`
other changes
> ansible-lint 6.x fixes

- tests/tasks/verify-role-results.yml
- tests/tests_fetch_keys_deploy_not_set.yml
- tests/tests_fetch_keys_deploy_set.yml
- tests/tests_nbde_server_service_state.yml
- tests/tests_tangd_custom_port.yml
This fixes errors like this:
```
[WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: __firewall_output_zone.stdout != "{{
nbde_server_firewall_zone }}"
```
In Ansible, `when`, `that` and other such conditionals are already
interpreted as Jinja expressions, so you usually don't need quoting
and {{ }}
> fix some more Jinja constructs

- tests/tests_tangd_custom_port.yml
The previous check already ensures that the given port is set
in the given zone - I'm not sure what the `--list-all` check is
supposed to do, except fail if the zone was changed before
running the test.
> Skip the check for firewall --list-all - not needed

- templates/tangd_socket_override.conf.j2
Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.
> Fingerprint RHEL System Role managed config files

- tests/tasks/check_header.yml
- tests/templates/get_ansible_managed.j2
- tests/tests_tangd_custom_port.yml
Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes these parameters.  `fingerprint` is required,
and one of `__file` or `__file_content`:
* `__file` - the full path of the file to check e.g. `/etc/realmd.conf`
* `__file_content` - the output of `slurp` of the file
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#adding-comments-to-fi …
> test: check generated files for ansible_managed, fingerprint

- README.md
For roles that use other system roles, they have a
`meta/collection-requirements.yml` file, and the README lists
these requirements and instructions.  However, these are only
required for github and Galaxy users, and not for users who
use the packaged roles, where it is confusing to see instructions
about installing requirements when none are needed.  We need to
make it easier to remove these sections when packaging.
Use regular heading style `#`, `##`, etc. rather than alternate
heading style in order to make it easier for the packaging parser
to fix the file.
Clean up some other markdownlint and ansible-lint issues.
> docs: use Collection requirements section in README

- README.md
The markdown to adoc to html conversion does not like headers
more than 72 characters long.
> fix: README.md headers should not be more than 72 characters

- .ansible-lint
- .ostree/get_ostree_data.sh
- meta/collection-requirements.yml
- tasks/main-tang.yml
- tasks/set_vars.yml
- tests/tasks/verify-role-results.yml
- tests/tests_tangd_custom_port.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
> refactor: improve support for ostree systems

- tests/tasks/cleanup.yml
- tests/tests_default.yml
- tests/tests_default_vars.yml
- tests/tests_deploy_keys.yml
- tests/tests_fetch_keys_deploy_not_set.yml
- tests/tests_fetch_keys_deploy_set.yml
- tests/tests_include_vars_from_parent.yml
- tests/tests_nbde_server_keys_dir.yml
- tests/tests_nbde_server_rotate_keys.yml
- tests/tests_nbde_server_service_state.yml
- tests/tests_tangd_custom_port.yml
I'm seeing several test flakes which I believe are due to
files/directories being left over after each run.  I've added
code to ensure cleanup:
* tests/tasks/cleanup.yml will remove leftover files/directories
from both the control node and the managed node
* Use `include_role` with `public: true` instead of `import_role`
in order to get role private variables
* Wrap tests in `block`/`always` to ensure clean up always runs
> tests: perform cleanup after each test

- tasks/tangd-custom-port.yml
- tests/tests_share_system_dir.yml
- tests/tests_tangd_custom_port.yml
- vars/main.yml
Cause: The role was assuming that the only file being managed in the tangd
socket override directory was the override.conf file for the custom port.
Consequence: The role would delete the directory if there was no custom port
without checking if there were other files in that directory being used to
override tangd settings.  This would cause the directory to be recreated
upon subsequent runs, and the role would report a change, and not appear
to be idempotent.
Fix: When adding the override directory for the port override file, do not
change its attributes.  Do not delete the directory if there are other files
in it.
Result: The role will co-exist with the tangd socket override files being
managed outside of the role.
Fixes …
> fix: Allow tangd socket override directory to be managed outside of the role

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
- .github/workflows/python-unit-test.yml
- .yamllint.yml
- tasks/tang-key-management.yml
- vars/main.yml
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

- tasks/tangd-custom-port.yml
Enhancement: Changes the behavior of the tasks managing selinux and firewall such that if the nbde_server_manage_selinux or nbde_server_manage_firewall variables are false, the appropriate role does not attempt to import.
Reason: I try to only install dependencies I absolutely need in dedicated directories for each project. This change makes it so that the selinux and firewall role dependencies are not needed if their features are not going to be used in that specific project.
Result: Users only need to install this role and not selinux or firewall in order to use this role.
Issue Tracker Tickets (Jira or BZ if any): N/A
> fix: Remove hard dependency on selinux and firewall roles
